services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: finbud-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps:/usr/src/app/apps
      - /usr/src/app/apps/frontend/.next
    working_dir: /app
    environment:
      - NX_IGNORE_PROJECTS=backend
    command: npx nx run frontend:dev --verbose
  # dynamodb-local:
  #  command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  #  image: "amazon/dynamodb-local:latest"
  #  container_name: dynamodb-local
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    - "./docker/dynamodb:/home/dynamodblocal/data"
  #  working_dir: /home/dynamodblocal
  # dynamodb: 
  #   image: "aaronshaf/dynamodb-admin"
  #   container_name: dynamodb-admin
  #   depends_on:
  #     - dynamodb-local
  #   restart: always
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - DYNAMO_ENDPOINT=http://dynamodb-local:8000
  #     - AWS_REGION=us-east-1

