version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci --cache .npm --prefer-offline
        build:
          commands:
            - echo "AUTH0_SECRET=$AUTH0_SECRET" >> apps/frontend/.env.production
            - echo "AUTH0_BASE_URL=$AUTH0_BASE_URL" >> apps/frontend/.env.production
            - echo "AUTH0_ISSUER_BASE_URL=$AUTH0_ISSUER_BASE_URL" >> apps/frontend/.env.production
            - echo "AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID" >> apps/frontend/.env.production
            - echo "AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET" >> apps/frontend/.env.production
            - echo "AUTH0_AUDIENCE=$AUTH0_AUDIENCE" >> apps/frontend/.env.production
            - echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> apps/frontend/.env.production
            - npx nx run frontend:build
      artifacts:
        baseDirectory: apps/frontend/.next
        files:
          - '**/*'
      cache:
        paths:
          - .next/cache/**/*
          - .npm/**/*
      buildPath: /
    appRoot: apps/frontend
