version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci --cache .npm --prefer-offline
        build:
          commands: 
            cat <<EOF >> .env.production
            AUTH0_BASE_URL=$AUTH0_BASE_URL
            AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
            AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
            AUTH0_ISSUER_BASE_URL=$AUTH0_ISSUER_BASE_URL
            AUTH0_SECRET=$AUTH0_SECRET
            EOF
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - .next/cache/**/*
          - .npm/**/*
    appRoot: FinBud-Frontend
